### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by mbirth** [KuromeSan/eCDP-Serial-Code#1]
The second number you're asked for is the DS Cartridge's serial number. This can be any number (as indicated by the "e.g. 000001" in the question).

**Comment by LiEnby** [comment]
Lol nice. I litterally just used Google translate so I wasn't expecting the best translations xD

Funny it's 'cartridge serial number' since the game makes no attempt to verify what you enter for it at all.. xD

**Comment by mbirth** [comment]
My guess is they bundled the cartridge with the DS and so the password they've sent to the employee only worked with that specific DS (MAC address) and specific cartridge (serial number).

**Comment by LiEnby** [comment]
But what about the store number ????

**Comment by LiEnby** [comment]
Anyway, gonna ask some of my japanese friends what it says- ;-;

**Comment by LiEnby** [comment]
@Princess-of-Sleeping said it was like "Typing shop management number for DS card" 
so perhaps were both kinda right xD- ill change it to "Enter McDonalds 'Store Management Number of DS Card' (second 6 digit entry):"
