### ISSUE TITLE
Try to get rid of gets_s

### ISSUE THREAD

**Issue by mbirth** [KuromeSan/eCDP-Serial-Code#2]
`gets_s` seems to be [a bit problematic](https://stackoverflow.com/a/12897143).

Also, it doesn't compile with GCC unless you [add the function manually](https://stackoverflow.com/questions/15149168/undefined-reference-to-gets-s).

**Comment by LiEnby** [comment]
Didn't know that, just knew never to use gets() normal xD 

Also uintptr and intptr don't seem to work on gcc either :(

**Comment by LiEnby** [comment]
fixed - https://github.com/KuromeSan/eCDP-Serial-Code/commit/b72083dfe26a99eab5a390c34b14e5cc718d9866
